# Generated by Django 6.0.3 on 2026-04-19 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemanagment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('dedicated_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='timetracker',
            name='unique_user_time',
        ),
        migrations.AddConstraint(
            model_name='timetracker',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_task'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='timemanagment.timetracker'),
        ),
        migrations.RemoveField(
            model_name='timetracker',
            name='dedicated_time',
        ),
        migrations.AddConstraint(
            model_name='tasklog',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_task_date'),
        ),
    ]
