# Generated by Django 6.0.3 on 2026-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
