# Generated by Django 6.0.3 on 2026-04-06 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebit',
            name='name',
            field=models.CharField(max_length=112, unique=True),
        ),
        migrations.AddConstraint(
            model_name='hebit',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_habit'),
        ),
    ]
