# Generated by Django 6.0.3 on 2026-04-14 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_hebit_name_hebit_unique_user_habit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebit',
            name='name',
            field=models.CharField(max_length=112),
        ),
        migrations.CreateModel(
            name='HabitComittment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked_mode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hebit',
            name='commitment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habits.habitcomittment'),
            preserve_default=False,
        ),
    ]
