# Generated by Django 6.0.3 on 2026-05-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_hebit_is_active_alter_habitcomittment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebit',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='hebitlog',
            name='completed',
        ),
        migrations.DeleteModel(
            name='HabitComittment',
        ),
    ]
