# Generated by Django 6.0.3 on 2026-05-16 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_hebit_commitment_remove_hebitlog_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebitlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
