# Generated by Django 6.0.3 on 2026-05-20 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_hebitlog_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hebit',
            name='unique_user_habit',
        ),
        migrations.AddConstraint(
            model_name='hebit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_active_user_habit'),
        ),
    ]
