# Generated by Django 6.0.3 on 2026-05-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_remove_hebit_unique_user_habit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebit',
            name='deactivated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
